export const DEMO_FILTERS = ["All", "Studio", "Lighting", "Pose", "Background", "Accessories", "Expression", "Child"];

export const DEMO_PORTRAITS = [
  {
    id: "neutral-white",
    title: "Neutral white backdrop",
    category: "Studio",
    path: "assets/demo/pexels-37230367.jpg",
    sourceId: "37230367",
    lesson: "A strong starting point for crop, eye line and file-size formatting.",
  },
  {
    id: "neutral-man",
    title: "Neutral studio portrait",
    category: "Studio",
    path: "assets/demo/pexels-14599188.jpg",
    sourceId: "14599188",
    lesson: "Check whether clean framing stays consistent across square and 35 x 45 programmes.",
  },
  {
    id: "hijab-white",
    title: "Head covering edges",
    category: "Accessories",
    path: "assets/demo/pexels-31642467.jpg",
    sourceId: "31642467",
    lesson: "Tests full head covering visibility, edge preservation and top margin.",
  },
  {
    id: "senior-neutral",
    title: "Senior portrait",
    category: "Studio",
    path: "assets/demo/pexels-12645006.jpg",
    sourceId: "12645006",
    lesson: "Tests natural skin detail without artificial smoothing or face restoration.",
  },
  {
    id: "glasses-neutral",
    title: "Glasses and glare",
    category: "Accessories",
    path: "assets/demo/pexels-30975992.jpg",
    sourceId: "30975992",
    lesson: "Shows glare detection and programme-specific eyeglasses guidance.",
  },
  {
    id: "glasses-white",
    title: "Glasses on white",
    category: "Accessories",
    path: "assets/demo/pexels-14564834.jpg",
    sourceId: "14564834",
    lesson: "A clean background with an accessory that some programmes do not accept.",
  },
  {
    id: "curly-close",
    title: "Close curly hair",
    category: "Studio",
    path: "assets/demo/pexels-36763532.jpg",
    sourceId: "36763532",
    lesson: "Tests crown detection, curl preservation and whether the source is cropped too tightly.",
  },
  {
    id: "curly-room",
    title: "Curly hair with room",
    category: "Studio",
    path: "assets/demo/pexels-36763536.jpg",
    sourceId: "36763536",
    lesson: "A wider source for comparing automatic crops across different destinations.",
  },
  {
    id: "side-profile",
    title: "Face turned sideways",
    category: "Pose",
    path: "assets/demo/pexels-7048311.jpg",
    sourceId: "7048311",
    lesson: "The model should recommend a retake instead of trying to manufacture a front-facing face.",
  },
  {
    id: "low-light-curls",
    title: "Low light and curls",
    category: "Lighting",
    path: "assets/demo/pexels-19039138.jpg",
    sourceId: "19039138",
    lesson: "Tests underexposure, shadow balance and complex hair against a dark background.",
  },
  {
    id: "senior-shadow",
    title: "Uneven senior lighting",
    category: "Lighting",
    path: "assets/demo/pexels-35466969.jpg",
    sourceId: "35466969",
    lesson: "Shows whether the system separates uneven lighting from focus and skin detail.",
  },
  {
    id: "child-reclining",
    title: "Child lying down",
    category: "Child",
    path: "assets/demo/pexels-31528535.jpg",
    sourceId: "31528535",
    lesson: "A deliberate retake case for orientation, posture and child-photo guidance.",
  },
  {
    id: "outdoor-sunglasses",
    title: "Outdoor sunglasses",
    category: "Accessories",
    path: "assets/demo/px_1043471.jpg",
    sourceId: "1043471",
    lesson: "Tests dark lenses, outdoor background and a hand near the face.",
  },
  {
    id: "city-glasses",
    title: "City background and glasses",
    category: "Background",
    path: "assets/demo/px_1239291.jpg",
    sourceId: "1239291",
    lesson: "Shows how a good face can still need a new capture because of background and glare.",
  },
  {
    id: "red-jacket-street",
    title: "Street portrait",
    category: "Background",
    path: "assets/demo/px_1681010.jpg",
    sourceId: "1681010",
    lesson: "A useful stress test for curly edges, shoulder crop and a detailed background.",
  },
  {
    id: "glasses-smile",
    title: "Glasses with smile",
    category: "Expression",
    path: "assets/demo/px_220453.jpg",
    sourceId: "220453",
    lesson: "Compares expression and eyeglasses rules without changing the subject's face.",
  },
  {
    id: "leaning-shoulders",
    title: "Leaning shoulders",
    category: "Pose",
    path: "assets/demo/px_2379004.jpg",
    sourceId: "2379004",
    lesson: "Tests body lean, shoulder level and whether framing guidance remains specific.",
  },
  {
    id: "hat-and-hand",
    title: "Hat and hand occlusion",
    category: "Accessories",
    path: "assets/demo/px_2613260.jpg",
    sourceId: "2613260",
    lesson: "A deliberate failure case for headwear, hand position and facial obstruction.",
  },
  {
    id: "off-centre-room",
    title: "Off-centre source",
    category: "Pose",
    path: "assets/demo/px_3763188.jpg",
    sourceId: "3763188",
    lesson: "Shows automatic centring when the source has enough room around the head.",
  },
  {
    id: "split-light",
    title: "Strong split lighting",
    category: "Lighting",
    path: "assets/demo/px_614810.jpg",
    sourceId: "614810",
    lesson: "Tests whether severe face-side shadow is flagged even when the image is sharp.",
  },
  {
    id: "outdoor-expression",
    title: "Outdoor smile",
    category: "Expression",
    path: "assets/demo/px_762020.jpg",
    sourceId: "762020",
    lesson: "Separates an expression warning from background and framing findings.",
  },
  {
    id: "broad-smile",
    title: "Broad studio smile",
    category: "Expression",
    path: "assets/demo/px_774909.jpg",
    sourceId: "774909",
    lesson: "A well-lit source that should still trigger neutral-expression guidance.",
  },
  {
    id: "dark-monochrome",
    title: "Dark monochrome portrait",
    category: "Lighting",
    path: "assets/demo/px_91227.jpg",
    sourceId: "91227",
    lesson: "Tests low exposure, monochrome input and difficult dark hair edges.",
  },
  {
    id: "casual-outdoor",
    title: "Casual outdoor photo",
    category: "Background",
    path: "assets/demo/px_936119.jpg",
    sourceId: "936119",
    lesson: "Shows why a pleasant portrait is not automatically an acceptable application photo.",
  },
];
