export const RULE_PROFILES = [
  {
    id: "us-passport-print-2026-06",
    allowedEdits: {
      straighten: true,
      tone: true,
      lighting: true,
      background: true,
      enhance: true,
      rescue: false,
      note: "US State Dept: photo must not be digitally altered to change your appearance. Framing/straightening OK; tone & background handled conservatively and flagged for review; AI face restoration not permitted.",
    },
    label: "United States passport - print",
    country: "US",
    countryName: "United States",
    programme: "Passport photo",
    category: "Passport",
    document: "Passport",
    delivery: "Print",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "U.S. State Department passport photos",
        url: "https://travel.state.gov/en/passports/apply/help/photos.html",
      },
    ],
    requirements: [
      "2 x 2 in / 51 x 51 mm color photo",
      "Head 25-35 mm from chin to top of head",
      "Plain white or off-white background",
      "Neutral expression, eyes open, no eyeglasses",
    ],
    output: {
      widthPx: 600,
      heightPx: 600,
      printWidthMm: 51,
      printHeightMm: 51,
      mime: "image/jpeg",
      quality: 0.92,
    },
    head: {
      measure: "chin_to_top_of_head",
      minMm: 25,
      maxMm: 35,
      minPercent: 50,
      maxPercent: 69,
      targetPercent: 62,
      topMarginPercent: 13,
      // U.S. State Dept: eyes 1-1/8 to 1-3/8 in from the bottom of a 2 in photo.
      // Encoded here as eye height measured from the TOP of the frame.
      eye: {
        fromTopMinPercent: 31,
        fromTopMaxPercent: 44,
        targetFromTopPercent: 37.5,
        note: "Eyes 28-35mm from bottom of a 51mm photo (State Dept).",
      },
    },
    background: {
      mode: "white_or_off_white",
      minEdgeLuma: 190,
      maxEdgeSaturation: 52,
      maxEdgeSpread: 42,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: null,
      maxBytes: null,
    },
    automation: {
      backgroundReplacement: true,
      backgroundColor: "#ffffff",
      enhanceOutput: true,
      compressionTarget: null,
    },
    reviewChecks: ["neutral expression", "eyes open", "mouth closed", "no face covering"],
  },
  {
    id: "us-visa-ds160-digital-2026-06",
    allowedEdits: {
      straighten: true,
      tone: true,
      lighting: true,
      background: true,
      enhance: true,
      rescue: false,
      note: "US visa photos follow the same no-alteration standard: conservative tone/background flagged; AI restoration not permitted.",
    },
    label: "United States visa - DS-160 digital",
    country: "US",
    countryName: "United States",
    programme: "Visa / DS-160",
    category: "Visa",
    document: "Visa",
    delivery: "Digital",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "U.S. State Department visa photos",
        url: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html",
      },
    ],
    requirements: [
      "Square digital image, usually 600 x 600 px or larger",
      "Printed equivalent is 2 x 2 in / 51 x 51 mm",
      "Head 22-35 mm or 50-69% of image height",
      "Plain white or off-white background",
    ],
    output: {
      widthPx: 600,
      heightPx: 600,
      printWidthMm: 51,
      printHeightMm: 51,
      mime: "image/jpeg",
      quality: 0.9,
    },
    head: {
      measure: "chin_to_top_of_head",
      minMm: 22,
      maxMm: 35,
      minPercent: 50,
      maxPercent: 69,
      targetPercent: 62,
      topMarginPercent: 12,
      eye: {
        fromTopMinPercent: 31,
        fromTopMaxPercent: 44,
        targetFromTopPercent: 37.5,
        note: "Eyes 22-35mm from bottom of a 51mm photo (State Dept visa).",
      },
    },
    background: {
      mode: "white_or_off_white",
      minEdgeLuma: 190,
      maxEdgeSaturation: 52,
      maxEdgeSpread: 42,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: null,
      maxBytes: 240000,
    },
    automation: {
      backgroundReplacement: true,
      backgroundColor: "#ffffff",
      enhanceOutput: true,
      compressionTarget: 240000,
    },
    reviewChecks: ["neutral expression", "eyes open", "mouth closed", "no eyeglasses"],
  },
  {
    id: "us-dv-lottery-digital-2026-06",
    allowedEdits: {
      straighten: true,
      tone: true,
      lighting: true,
      background: true,
      enhance: true,
      rescue: false,
      note: "DV programme explicitly rejects digitally retouched photos. Conservative corrections flagged; AI restoration not permitted.",
    },
    label: "United States diversity visa - digital",
    country: "US",
    countryName: "United States",
    programme: "Diversity Visa / DV Lottery",
    category: "Visa",
    document: "Diversity Visa",
    delivery: "Digital",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "U.S. State Department visa photo requirements",
        url: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html",
      },
    ],
    requirements: [
      "Square JPEG digital photo",
      "Use the same composition standard as U.S. visa photos",
      "Head 50-69% of image height",
      "White or off-white background",
    ],
    output: {
      widthPx: 600,
      heightPx: 600,
      printWidthMm: 51,
      printHeightMm: 51,
      mime: "image/jpeg",
      quality: 0.88,
    },
    head: {
      measure: "chin_to_top_of_head",
      minMm: 22,
      maxMm: 35,
      minPercent: 50,
      maxPercent: 69,
      targetPercent: 62,
      topMarginPercent: 12,
      eye: {
        fromTopMinPercent: 31,
        fromTopMaxPercent: 44,
        targetFromTopPercent: 37.5,
        note: "DV uses the U.S. visa composition: eyes 22-35mm from bottom of a 51mm photo.",
      },
    },
    background: {
      mode: "white_or_off_white",
      minEdgeLuma: 190,
      maxEdgeSaturation: 52,
      maxEdgeSpread: 42,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: null,
      maxBytes: 240000,
    },
    automation: {
      backgroundReplacement: true,
      backgroundColor: "#ffffff",
      enhanceOutput: true,
      compressionTarget: 240000,
    },
    reviewChecks: ["recent photo", "neutral expression", "eyes open", "no digital retouching"],
  },
  {
    id: "uk-passport-digital-2026-06",
    allowedEdits: {
      straighten: true,
      tone: true,
      lighting: true,
      background: true,
      enhance: true,
      rescue: false,
      note: "GOV.UK: the photo must be a true likeness and must not be edited in a way that changes your appearance. AI restoration not permitted.",
    },
    label: "United Kingdom passport - digital",
    country: "GB",
    countryName: "United Kingdom",
    programme: "Passport digital upload",
    category: "Passport",
    document: "Passport",
    delivery: "Digital",
    lastReviewed: "2026-06-23",
    sources: [
      {
        label: "GOV.UK digital passport photos",
        url: "https://www.gov.uk/photos-for-passports",
      },
      {
        label: "GOV.UK photo standards",
        url: "https://www.gov.uk/government/publications/photographic-standards/photo-standards-accessible",
      },
    ],
    requirements: [
      "Digital portrait with plain light background",
      "Face clear and centered",
      "Neutral expression, mouth closed, eyes open",
      "No editing that changes appearance",
    ],
    output: {
      widthPx: 900,
      heightPx: 1125,
      printWidthMm: null,
      printHeightMm: null,
      mime: "image/jpeg",
      quality: 0.92,
    },
    head: {
      // GOV.UK: head must be 29-34mm from chin to CROWN (top of skull, not hair).
      // Applied here as the equivalent proportion of the frame.
      measure: "chin_to_crown",
      minMm: 29,
      maxMm: 34,
      minPercent: 62,
      maxPercent: 76,
      targetPercent: 69,
      topMarginPercent: 8,
    },
    background: {
      mode: "plain_light",
      minEdgeLuma: 170,
      maxEdgeSaturation: 70,
      maxEdgeSpread: 50,
    },
    file: {
      formats: ["jpg", "jpeg", "png"],
      minBytes: null,
      maxBytes: null,
    },
    automation: {
      backgroundReplacement: true,
      backgroundColor: "#f7f7f2",
      enhanceOutput: true,
      compressionTarget: null,
    },
    reviewChecks: ["true likeness", "neutral expression", "plain background", "no digital retouching"],
  },
  {
    id: "india-passport-icao-upload-2026-06",
    allowedEdits: {
      straighten: true,
      tone: false,
      lighting: false,
      background: false,
      enhance: false,
      rescue: false,
      note: "Passport Seva ICAO guidance requires an unaltered photograph: crop & straighten only. Retake against a white wall instead of editing the background.",
    },
    label: "India passport - ICAO upload",
    country: "IN",
    countryName: "India",
    programme: "Passport ICAO upload",
    category: "Passport",
    document: "Passport",
    delivery: "Digital",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "Passport Seva ICAO photo guidelines",
        url: "https://portal5.passportindia.gov.in/Online/pdf/Guidelines_for_ICAO_Compliant_Photographs_for_Passport_Applications.pdf",
      },
      {
        label: "Passport Seva FAQ",
        url: "https://www.passportindia.gov.in/psp/FaqServicesAvailable",
      },
    ],
    requirements: [
      "ICAO-style front-facing portrait",
      "White background",
      "Face occupies most of the image",
      "Natural expression, eyes visible, no head tilt",
    ],
    // Passport Seva ICAO guidance is a 2 in x 2 in (51 x 51 mm) SQUARE photo, not
    // the previous 630 x 810 portrait. Head sizing follows the ICAO 2x2 chin-to-top
    // composition (~62-78% of frame). Confirm exact portal pixel bounds before a
    // paid launch; the server-side profile registry is the authoritative copy.
    output: {
      widthPx: 600,
      heightPx: 600,
      printWidthMm: 51,
      printHeightMm: 51,
      mime: "image/jpeg",
      quality: 0.9,
    },
    head: {
      measure: "chin_to_top_of_head",
      minMm: 25,
      maxMm: 35,
      minPercent: 62,
      maxPercent: 78,
      targetPercent: 70,
      topMarginPercent: 8,
    },
    background: {
      mode: "white",
      minEdgeLuma: 195,
      maxEdgeSaturation: 45,
      maxEdgeSpread: 38,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: 10000,
      maxBytes: 250000,
    },
    automation: {
      backgroundReplacement: false,
      backgroundColor: "#ffffff",
      enhanceOutput: false,
      compressionTarget: 250000,
    },
    reviewChecks: ["natural expression", "eyes visible", "no head tilt", "unaltered photo"],
  },
  {
    id: "india-visa-online-digital-2026-06",
    allowedEdits: {
      straighten: true,
      tone: true,
      lighting: true,
      background: true,
      enhance: true,
      rescue: false,
      note: "e-Visa upload accepts photo-lab preparation; corrections stay conservative and flagged. AI restoration not permitted.",
    },
    label: "India visa online - digital upload",
    country: "IN",
    countryName: "India",
    programme: "Visa Online / e-Visa",
    category: "Visa",
    document: "Visa",
    delivery: "Digital",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "India Visa Online instructions",
        url: "https://indianvisaonline.gov.in/visa/instruction.html",
      },
      {
        label: "India e-Visa upload guidance",
        url: "https://indianvisaonline.gov.in/evisa/",
      },
    ],
    requirements: [
      "Square color digital photo",
      "White background",
      "Minimum 350 x 350 px",
      "Maximum file size 1 MB",
    ],
    output: {
      widthPx: 600,
      heightPx: 600,
      printWidthMm: 51,
      printHeightMm: 51,
      mime: "image/jpeg",
      quality: 0.9,
    },
    head: {
      measure: "chin_to_top_of_head",
      minMm: 25,
      maxMm: 35,
      minPercent: 49,
      maxPercent: 69,
      targetPercent: 62,
      topMarginPercent: 12,
    },
    background: {
      mode: "white",
      minEdgeLuma: 195,
      maxEdgeSaturation: 45,
      maxEdgeSpread: 38,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: 10000,
      maxBytes: 1000000,
    },
    automation: {
      backgroundReplacement: true,
      backgroundColor: "#ffffff",
      enhanceOutput: true,
      compressionTarget: 1000000,
    },
    reviewChecks: ["front view", "full face visible", "eyes open", "no shadows"],
  },
  {
    id: "canada-passport-print-2026-06",
    allowedEdits: {
      straighten: true,
      tone: false,
      lighting: false,
      background: false,
      enhance: false,
      rescue: false,
      note: "Canada: the photo must NOT be altered in any way (including filters and AI tools). Crop & straighten only; two identical prints from a commercial photographer.",
    },
    label: "Canada passport - print",
    country: "CA",
    countryName: "Canada",
    programme: "Passport photo (print)",
    category: "Passport",
    document: "Passport",
    delivery: "Print",
    lastReviewed: "2026-06-23",
    sources: [
      {
        label: "Canada passport photo requirements",
        url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/canadian-passports/photos.html",
      },
    ],
    requirements: [
      "TWO identical 50 x 70 mm printed photos",
      "Head 31-36 mm from chin to crown",
      "Taken/printed by a commercial photographer; home prints rejected",
      "Must NOT be altered or edited in any way (no filters, AI, or background editing)",
      "Plain white or light-coloured background",
    ],
    output: {
      widthPx: 1000,
      heightPx: 1400,
      printWidthMm: 50,
      printHeightMm: 70,
      mime: "image/jpeg",
      quality: 0.95,
    },
    head: {
      measure: "chin_to_crown",
      minMm: 31,
      maxMm: 36,
      minPercent: 44,
      maxPercent: 51,
      targetPercent: 47.5,
      topMarginPercent: 13,
    },
    background: {
      mode: "white_or_light",
      minEdgeLuma: 180,
      maxEdgeSaturation: 58,
      maxEdgeSpread: 42,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: null,
      maxBytes: null,
    },
    automation: {
      backgroundReplacement: false,
      backgroundColor: "#ffffff",
      enhanceOutput: false,
      compressionTarget: null,
    },
    reviewChecks: ["commercial photographer required", "unaltered photo", "two identical prints", "neutral expression"],
  },
  {
    id: "canada-trv-print-2026-06",
    allowedEdits: {
      straighten: true,
      tone: false,
      lighting: false,
      background: false,
      enhance: false,
      rescue: false,
      note: "IRCC: digital photographs must not be altered in any way. Crop & straighten only.",
    },
    label: "Canada temporary resident visa - print",
    country: "CA",
    countryName: "Canada",
    programme: "Temporary resident visa",
    category: "Visa",
    document: "Temporary Resident Visa",
    delivery: "Print",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "Canada temporary resident visa photograph specifications",
        url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/application/application-forms-guides/temporary-resident-visa-application-photograph-specifications.html",
      },
    ],
    requirements: [
      "35 x 45 mm photo",
      "Head 31-36 mm from chin to crown",
      "White or light-colored background",
      "Digital photographs must not be altered",
    ],
    output: {
      widthPx: 826,
      heightPx: 1063,
      printWidthMm: 35,
      printHeightMm: 45,
      mime: "image/jpeg",
      quality: 0.92,
    },
    head: {
      measure: "chin_to_crown",
      minMm: 31,
      maxMm: 36,
      minPercent: 69,
      maxPercent: 80,
      targetPercent: 74,
      topMarginPercent: 8,
    },
    background: {
      mode: "white_or_light",
      minEdgeLuma: 180,
      maxEdgeSaturation: 58,
      maxEdgeSpread: 42,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: null,
      maxBytes: null,
    },
    automation: {
      backgroundReplacement: false,
      backgroundColor: "#ffffff",
      enhanceOutput: false,
      compressionTarget: null,
    },
    reviewChecks: ["unaltered photo", "neutral expression", "eyes visible"],
  },
  {
    id: "australia-passport-print-2026-06",
    allowedEdits: {
      straighten: true,
      tone: false,
      lighting: false,
      background: false,
      enhance: false,
      rescue: false,
      note: "Australian Passport Office: the photo must not be digitally enhanced or altered. Crop & straighten only.",
    },
    label: "Australia passport - print",
    country: "AU",
    countryName: "Australia",
    programme: "Passport photo",
    category: "Passport",
    document: "Passport",
    delivery: "Print",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "Australian Passport Office photo guidelines",
        url: "https://www.passports.gov.au/PhotoGuidelines",
      },
    ],
    requirements: [
      "35 x 45 mm photo",
      "Head 32-36 mm from chin to crown",
      "Plain white or light-gray background",
      "No retouching or alteration",
    ],
    output: {
      widthPx: 1400,
      heightPx: 1800,
      printWidthMm: 35,
      printHeightMm: 45,
      mime: "image/jpeg",
      quality: 0.92,
    },
    head: {
      measure: "chin_to_crown",
      minMm: 32,
      maxMm: 36,
      minPercent: 71,
      maxPercent: 80,
      targetPercent: 75.5,
      topMarginPercent: 8,
    },
    background: {
      mode: "white_or_light",
      minEdgeLuma: 180,
      maxEdgeSaturation: 58,
      maxEdgeSpread: 42,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: null,
      maxBytes: null,
    },
    automation: {
      backgroundReplacement: false,
      backgroundColor: "#f7f7f2",
      enhanceOutput: false,
      compressionTarget: null,
    },
    reviewChecks: ["no retouching", "edges of face visible", "no head tilt", "glossy print workflow"],
  },
  {
    id: "france-schengen-visa-print-2026-06",
    allowedEdits: {
      straighten: true,
      tone: true,
      lighting: true,
      background: true,
      enhance: true,
      rescue: false,
      note: "ICAO standard: facial features must not be retouched. Conservative tone/background flagged; AI restoration not permitted.",
    },
    label: "France / Schengen visa - print",
    country: "FR",
    countryName: "France",
    programme: "Schengen visa",
    category: "Visa",
    document: "Visa",
    delivery: "Print",
    lastReviewed: "2026-06-07",
    sources: [
      {
        label: "France-Visas photograph instructions",
        url: "https://france-visas.gouv.fr/documents/d/france-visas/iso_iec_fv_visa_photograph_requirements_en",
      },
    ],
    requirements: [
      "35 x 45 mm photo",
      "Face centered and front-facing",
      "Plain light background",
      "Neutral expression, mouth closed, eyes visible",
    ],
    output: {
      widthPx: 826,
      heightPx: 1063,
      printWidthMm: 35,
      printHeightMm: 45,
      mime: "image/jpeg",
      quality: 0.92,
    },
    head: {
      measure: "face_area_estimate",
      minMm: null,
      maxMm: null,
      minPercent: 70,
      maxPercent: 80,
      targetPercent: 75,
      topMarginPercent: 8,
    },
    background: {
      mode: "plain_light",
      minEdgeLuma: 170,
      maxEdgeSaturation: 70,
      maxEdgeSpread: 50,
    },
    file: {
      formats: ["jpg", "jpeg"],
      minBytes: null,
      maxBytes: null,
    },
    automation: {
      backgroundReplacement: true,
      backgroundColor: "#f7f7f2",
      enhanceOutput: true,
      compressionTarget: null,
    },
    reviewChecks: ["neutral expression", "mouth closed", "eyes visible", "no other person visible"],
  },
];

export const COUNTRIES = Array.from(
  new Map(RULE_PROFILES.map((profile) => [profile.country, { code: profile.country, name: profile.countryName }])).values(),
).sort((a, b) => a.name.localeCompare(b.name));

export function getDefaultProfile() {
  return RULE_PROFILES[0];
}

export function getProfilesForCountry(countryCode) {
  return RULE_PROFILES.filter((profile) => profile.country === countryCode);
}
